### ISSUE TITLE
Нужен метод, отменяющий все текущие активные запросы

### ISSUE THREAD

**Issue by Sshwift** [LimeHD/ios-api-module#5]
В Alamofire это работало так, к примеру:
sessionManager.session.getTasksWithCompletionHandler { (sessionDataTask, uploadData, downloadData) in
            sessionDataTask.forEach { $0.cancel() }
            uploadData.forEach { $0.cancel() }
            downloadData.forEach { $0.cancel() }
        }

**Comment by Algashev** [comment]
При инициализации клиента есть возможность задать параметр `session`:
``` swift
public init(baseUrl: String, session: URLSession = URLSession.shared, mainQueue: Dispatchable = DispatchQueue.main)
```
Для отмены запросов все аналогично `Alamofire` (пример, при использованию параметра `session` по умолчанию - `URLSession.shared`):
``` swift
URLSession.shared.getTasksWithCompletionHandler { (sessionDataTask, uploadData, downloadData) in
    sessionDataTask.forEach { $0.cancel() }
    uploadData.forEach { $0.cancel() }
    downloadData.forEach { $0.cancel() }
}
```
